spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/store_api?createDatabaseIfNotExist=true
    username: root
    password: 5396rudiger
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 5m
    refreshTokenExpiration: 604800 # 7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}