spring:
  datasource:
    url: jdbc:mysql://localhost:3307/store_api?createDatabaseIfNotExist=true
    username: root
    password: 5396rudiger
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242